#!/usr/bin/env bash
dir="$HOME/Pictures/Wallpapers/static"
mkdir -p "$dir"
find "$dir" -maxdepth 1 -type f \( \
  -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' -o -iname '*.gif' \
\) | sort
