#!/usr/bin/env python3

import argparse
import json
import os
import re
import subprocess
import sys
import shutil
import time
from pathlib import Path


BASE = Path(__file__).resolve().parents[1]

PYWAL_SCRIPT = BASE / "scripts" / "velora-pywal-theme.py"
PYWAL_THEME_PATH = BASE / "themes" / "pywal16.json"

WAL_PATH = Path(
    os.path.expanduser("~/.cache/wal/colors.json")
)

STATE_DIR = (
    Path(
        os.environ.get(
            "XDG_STATE_HOME",
            Path.home() / ".local/state",
        )
    )
    / "velora-shell"
)

STATE_PATH = STATE_DIR / "terminal-theme.json"

STRONG_COLORS_PATH = (
    STATE_DIR / "terminal-strong-colors"
)

# Kitty roda usando o XDG_CONFIG_HOME do usuário,
# não o ambiente isolado do Shell.
KITTY_DIR = (
    Path(
        os.environ.get(
            "VELORA_HOST_XDG_CONFIG_HOME",
            Path.home() / ".config",
        )
    )
    / "kitty"
)

KITTY_CONF = KITTY_DIR / "kitty.conf"

KITTY_THEME = (
    KITTY_DIR / "velora-pywal.conf"
)

# Kitty can automatically re-apply one of these theme fragments after the
# normal kitty.conf has already been loaded. If they keep an old theme, they
# override the palette generated by Velora. We keep every existing automatic
# theme file synchronized with the Velora-generated theme.
KITTY_AUTO_THEMES = (
    KITTY_DIR / "dark-theme.auto.conf",
    KITTY_DIR / "light-theme.auto.conf",
    KITTY_DIR / "no-preference-theme.auto.conf",
)


MANAGED_KEYS = {
    "foreground",
    "background",
    "background_opacity",
    "cursor",
    "cursor_text_color",
    "selection_background",
    "selection_foreground",
    "active_tab_foreground",
    "active_tab_background",
    "inactive_tab_foreground",
    "inactive_tab_background",
    "active_border_color",
    "inactive_border_color",
    "bell_border_color",
}


def clamp(value, low=0, high=255):
    return max(
        low,
        min(
            high,
            int(round(value)),
        ),
    )


def hex_to_rgb(value):
    value = (
        str(value or "")
        .strip()
        .lstrip("#")
    )

    if len(value) != 6:
        raise ValueError(
            "invalid hex color"
        )

    return tuple(
        int(
            value[i:i + 2],
            16,
        )
        for i in (0, 2, 4)
    )


def rgb_to_hex(rgb):
    return "#{:02x}{:02x}{:02x}".format(
        *(
            clamp(value)
            for value in rgb
        )
    )


def mix(a, b, amount):
    amount = max(
        0.0,
        min(
            1.0,
            float(amount),
        ),
    )

    return tuple(
        a[i]
        + (
            b[i] - a[i]
        )
        * amount
        for i in range(3)
    )


def lighten(color, amount):
    return rgb_to_hex(
        mix(
            hex_to_rgb(color),
            (255, 255, 255),
            amount,
        )
    )


def darken(color, amount):
    return rgb_to_hex(
        mix(
            hex_to_rgb(color),
            (0, 0, 0),
            amount,
        )
    )


def luminance(color):
    def channel(value):
        value /= 255

        if value <= 0.03928:
            return value / 12.92

        return (
            (
                value + 0.055
            )
            / 1.055
        ) ** 2.4

    r, g, b = (
        channel(value)
        for value
        in hex_to_rgb(color)
    )

    return (
        0.2126 * r
        + 0.7152 * g
        + 0.0722 * b
    )


def text_on(color):
    return (
        "#ffffff"
        if luminance(color) < 0.42
        else "#202124"
    )


def read_json(path):
    try:
        return json.loads(
            path.read_text(
                encoding="utf-8"
            )
        )

    except Exception:
        return {}


def rgba_to_hex(
    value,
    fallback,
):
    """
    Converte QColor/rgba para RGB.

    Aceita:
      #RRGGBB
      #AARRGGBB
      rgba(r,g,b,a)
      rgba(0..1)
    """

    value = str(value or "").strip()

    if (
        value.startswith("#")
        and len(value) == 7
    ):
        return value.lower()

    # Qt frequentemente serializa QColor
    # como #AARRGGBB.
    if (
        value.startswith("#")
        and len(value) == 9
    ):
        return (
            "#"
            + value[3:]
        ).lower()

    if value.startswith("rgba("):
        try:
            parts = [
                float(part.strip())
                for part
                in value[5:-1].split(",")
            ]

            rgb = parts[:3]

            if (
                rgb
                and max(rgb) <= 1.0
            ):
                rgb = [
                    channel * 255
                    for channel
                    in rgb
                ]

            return rgb_to_hex(rgb)

        except Exception:
            return fallback

    return fallback


def qcolor_rgb_alpha(
    value,
    fallback_rgb,
    fallback_alpha=0.56,
):
    """
    Retorna RGB e alpha separadamente.

    Isso é essencial porque:

        #71000000

    significa:

        alpha = 0x71
        RGB   = 000000

    e NÃO preto sólido.
    """

    value = str(value or "").strip()

    if (
        value.startswith("#")
        and len(value) == 9
    ):
        try:
            alpha = (
                int(
                    value[1:3],
                    16,
                )
                / 255.0
            )

            rgb = (
                "#"
                + value[3:]
            ).lower()

            return (
                rgb,
                alpha,
            )

        except Exception:
            pass

    if (
        value.startswith("#")
        and len(value) == 7
    ):
        return (
            value.lower(),
            fallback_alpha,
        )

    if value.startswith("rgba("):
        try:
            parts = [
                float(part.strip())
                for part
                in value[5:-1].split(",")
            ]

            rgb = parts[:3]

            if (
                rgb
                and max(rgb) <= 1.0
            ):
                rgb = [
                    value * 255
                    for value
                    in rgb
                ]

            alpha = (
                parts[3]
                if len(parts) >= 4
                else fallback_alpha
            )

            return (
                rgb_to_hex(rgb),
                max(
                    0.0,
                    min(
                        1.0,
                        alpha,
                    ),
                ),
            )

        except Exception:
            pass

    return (
        fallback_rgb,
        fallback_alpha,
    )


def load_pywal_theme():
    if PYWAL_SCRIPT.exists():
        try:
            result = subprocess.run(
                [
                    str(PYWAL_SCRIPT),
                    "--emit-or-generate",
                    "--no-ipc",
                ],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                timeout=2.0,
                check=False,
            )

            if (
                result.returncode == 0
                and result.stdout.strip()
            ):
                return json.loads(
                    result.stdout.strip()
                )

        except Exception:
            pass

    if PYWAL_THEME_PATH.exists():
        return json.loads(
            PYWAL_THEME_PATH.read_text(
                encoding="utf-8"
            )
        )

    raise RuntimeError(
        "pywal16 theme is not available"
    )


def load_live_velora_palette():
    """
    Pergunta diretamente ao Velora Shell
    qual superfície está sendo usada agora.

    Exemplo atual:

      bar:        #71000000
      foreground: #f6f4f1
    """

    try:
        result = subprocess.run(
            [
                "qs",
                "-p",
                str(BASE),
                "ipc",
                "call",
                "composition",
                "paletteState",
            ],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=1.5,
            check=False,
        )

        if result.returncode != 0:
            return {}

        output = result.stdout.strip()

        if not output:
            return {}

        return json.loads(output)

    except Exception:
        return {}


def strong_colors_enabled():
    try:
        value = (
            STRONG_COLORS_PATH
            .read_text(
                encoding="utf-8"
            )
            .strip()
            .lower()
        )

        return value in {
            "1",
            "true",
            "on",
            "enabled",
        }

    except Exception:
        return False


def soften_near_black(
    background,
    accent,
    dark,
):
    """
    Preto puro + transparência pode ficar visualmente
    "morto" em wallpapers escuros.

    Aplica só um vestígio da cor de accent.
    Não transforma o terminal em colorido.
    """

    if not dark:
        return background

    if luminance(background) > 0.018:
        return background

    try:
        return rgb_to_hex(
            mix(
                hex_to_rgb(background),
                hex_to_rgb(accent),
                0.075,
            )
        )

    except Exception:
        return background


def palette_from_theme(
    theme,
    wal,
):
    colors = (
        wal.get("colors", {})
        if isinstance(wal, dict)
        else {}
    )

    special = (
        wal.get("special", {})
        if isinstance(wal, dict)
        else {}
    )

    mode = str(
        theme.get("themeMode")
        or "dark"
    )

    dark = mode == "dark"

    live = load_live_velora_palette()

    wal_bg = str(
        special.get("background")
        or colors.get("color0")
        or (
            "#101010"
            if dark
            else "#f7f7f7"
        )
    )

    wal_fg = str(
        special.get("foreground")
        or colors.get("color7")
        or (
            "#f2edf7"
            if dark
            else "#202124"
        )
    )

    fallback_background = rgba_to_hex(
        theme.get("surfaceSidebar")
        or theme.get("surfaceBase"),
        (
            darken(
                wal_bg,
                0.04,
            )
            if dark
            else lighten(
                wal_bg,
                0.20,
            )
        ),
    )

    background, live_alpha = (
        qcolor_rgb_alpha(
            live.get("bar"),
            fallback_background,
            0.56,
        )
    )

    foreground = rgba_to_hex(
        live.get("foreground"),
        rgba_to_hex(
            theme.get("textPrimary"),
            wal_fg,
        ),
    )

    secondary = rgba_to_hex(
        theme.get("textSecondary"),
        (
            lighten(
                foreground,
                0.28,
            )
            if dark
            else darken(
                foreground,
                0.18,
            )
        ),
    )

    accent = rgba_to_hex(
        theme.get("accentPrimary"),
        str(
            colors.get("color4")
            or "#8da3ff"
        ),
    )

    accent2 = rgba_to_hex(
        theme.get("accentSecondary"),
        str(
            colors.get("color5")
            or accent
        ),
    )

    #
    # Evita preto absolutamente morto.
    #
    background = soften_near_black(
        background,
        accent,
        dark,
    )

    #
    # Materialidade do terminal.
    #
    # Não permitimos que uma barra sólida transforme
    # o Kitty numa parede opaca.
    #
    if dark:
        minimum_opacity = 0.40
        maximum_opacity = 0.62
    else:
        minimum_opacity = 0.52
        maximum_opacity = 0.76

    background_opacity = max(
        minimum_opacity,
        min(
            maximum_opacity,
            live_alpha,
        ),
    )

    strong_colors = (
        strong_colors_enabled()
    )

    if strong_colors and dark:
        background = darken(
            background,
            0.18,
        )

    #
    # ANSI.
    #
    # Mantemos a identidade pywal, mas o preto/branco
    # seguem a superfície atual do Velora.
    #
    ansi = {
        "color0":
            darken(
                background,
                0.30,
            )
            if dark
            else darken(
                background,
                0.68,
            ),

        "color1":
            str(
                colors.get("color1")
                or "#d93025"
            ),

        "color2":
            str(
                colors.get("color2")
                or "#188038"
            ),

        "color3":
            str(
                colors.get("color3")
                or "#b06000"
            ),

        "color4":
            str(
                colors.get("color4")
                or accent
            ),

        "color5":
            str(
                colors.get("color5")
                or accent2
            ),

        "color6":
            str(
                colors.get("color6")
                or "#007b83"
            ),

        "color7":
            lighten(
                background,
                0.60,
            )
            if dark
            else darken(
                background,
                0.05,
            ),
    }

    ansi.update({
        "color8":
            lighten(
                ansi["color0"],
                0.32,
            ),

        "color9":
            lighten(
                ansi["color1"],
                0.16,
            ),

        "color10":
            lighten(
                ansi["color2"],
                0.16,
            ),

        "color11":
            lighten(
                ansi["color3"],
                0.16,
            ),

        "color12":
            lighten(
                ansi["color4"],
                0.16,
            ),

        "color13":
            lighten(
                ansi["color5"],
                0.16,
            ),

        "color14":
            lighten(
                ansi["color6"],
                0.16,
            ),

        "color15":
            (
                lighten(
                    foreground,
                    0.12,
                )
                if dark
                else "#ffffff"
            ),
    })

    selection = (
        lighten(
            accent,
            0.44,
        )
        if luminance(accent) < 0.52
        else darken(
            accent,
            0.18,
        )
    )

    return {
        "mode":
            mode,

        "wallpaper":
            theme.get("wallpaper")
            or wal.get(
                "wallpaper",
                "",
            ),

        "checksum":
            theme.get("checksum")
            or wal.get(
                "checksum",
                "",
            ),

        "background":
            background,

        "background_opacity":
            background_opacity,

        "foreground":
            foreground,

        "secondary":
            secondary,

        "accent":
            accent,

        "selection":
            selection,

        "selection_text":
            text_on(selection),

        "strong_colors":
            strong_colors,

        **ansi,
    }


def generate_kitty_theme(
    palette,
):
    lines = [
        "# Generated by Velora Shell.",
        "# Terminal surface follows the live Velora bar.",
        f"# wallpaper {palette['wallpaper']}",
        (
            "# strong_colors "
            + (
                "on"
                if palette["strong_colors"]
                else "off"
            )
        ),

        "",

        f"foreground {palette['foreground']}",
        f"background {palette['background']}",

        (
            "background_opacity "
            f"{palette['background_opacity']:.3f}"
        ),

        f"cursor {palette['foreground']}",
        f"cursor_text_color {palette['background']}",

        (
            "selection_background "
            f"{palette['selection']}"
        ),

        (
            "selection_foreground "
            f"{palette['selection_text']}"
        ),

        "",

        (
            "active_tab_foreground "
            f"{palette['background']}"
        ),

        (
            "active_tab_background "
            f"{palette['accent']}"
        ),

        (
            "inactive_tab_foreground "
            f"{palette['secondary']}"
        ),

        (
            "inactive_tab_background "
            f"{palette['background']}"
        ),

        (
            "active_border_color "
            f"{palette['accent']}"
        ),

        (
            "inactive_border_color "
            f"{palette['background']}"
        ),

        (
            "bell_border_color "
            f"{palette['accent']}"
        ),

        "",
    ]

    for index in range(16):
        lines.append(
            f"color{index} "
            f"{palette[f'color{index}']}"
        )

    return (
        "\n".join(lines)
        + "\n"
    )


def is_managed_color_line(
    line,
):
    stripped = line.strip()

    if (
        not stripped
        or stripped.startswith("#")
    ):
        return False

    key = re.split(
        r"\s+",
        stripped,
        maxsplit=1,
    )[0]

    return (
        key in MANAGED_KEYS
        or re.fullmatch(
            r"color(?:[0-9]|1[0-5])",
            key or "",
        )
        is not None
    )


def ensure_kitty_include():
    KITTY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    lines = (
        KITTY_CONF
        .read_text(
            encoding="utf-8"
        )
        .splitlines()
        if KITTY_CONF.exists()
        else []
    )

    output = []

    include_seen = False

    for line in lines:
        stripped = line.strip()

        if (
            stripped
            == "include velora-pywal.conf"
        ):
            if not include_seen:
                output.append(line)
                include_seen = True

            continue

        if is_managed_color_line(line):
            continue

        output.append(line)

    if not include_seen:
        output.insert(
            0,
            "include velora-pywal.conf",
        )

        if (
            len(output) > 1
            and output[1].strip()
        ):
            output.insert(
                1,
                "",
            )

    KITTY_CONF.write_text(
        "\n".join(output).rstrip()
        + "\n",
        encoding="utf-8",
    )


def backup_auto_theme_once(path):
    """
    Preserve the user's original Kitty auto-theme before Velora starts
    managing it. Existing .before-velora-* backups are reused so repeated
    wallpaper changes do not create an unlimited pile of backups.
    """

    if not path.exists():
        return ""

    existing = sorted(
        KITTY_DIR.glob(
            path.name + ".before-velora-*"
        )
    )

    if existing:
        return str(existing[0])

    backup = KITTY_DIR / (
        path.name
        + ".before-velora-"
        + str(time.time_ns())
    )

    try:
        shutil.copy2(
            path,
            backup,
        )
        return str(backup)
    except Exception:
        return ""


def sync_kitty_auto_themes(theme_text):
    """
    Mirror the Velora theme into every Kitty automatic-theme fragment that
    already exists.

    Kitty's automatic theme mechanism can load these files after kitty.conf:
      dark-theme.auto.conf
      light-theme.auto.conf
      no-preference-theme.auto.conf

    Without this synchronization an old Kitty theme can overwrite Velora's
    colors again after a dark/light preference refresh or config reload.
    """

    KITTY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    synced = []
    backups = {}

    for path in KITTY_AUTO_THEMES:
        if not path.exists():
            continue

        backup = backup_auto_theme_once(
            path
        )

        if backup:
            backups[str(path)] = backup

        try:
            current = path.read_text(
                encoding="utf-8"
            )
        except Exception:
            current = ""

        if current != theme_text:
            path.write_text(
                theme_text,
                encoding="utf-8",
            )

        synced.append(
            str(path)
        )

    return synced, backups


def sync_terminal_theme():
    theme = load_pywal_theme()

    wal = read_json(
        WAL_PATH
    )

    palette = palette_from_theme(
        theme,
        wal,
    )

    KITTY_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    theme_text = generate_kitty_theme(
        palette
    )

    KITTY_THEME.write_text(
        theme_text,
        encoding="utf-8",
    )

    ensure_kitty_include()

    auto_themes, auto_theme_backups = (
        sync_kitty_auto_themes(
            theme_text
        )
    )

    STATE_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    STATE_PATH.write_text(
        json.dumps(
            {
                "terminal":
                    "kitty",

                "themeFile":
                    str(KITTY_THEME),

                "configFile":
                    str(KITTY_CONF),

                "wallpaper":
                    palette["wallpaper"],

                "checksum":
                    palette["checksum"],

                "background":
                    palette["background"],

                "backgroundOpacity":
                    palette[
                        "background_opacity"
                    ],

                "foreground":
                    palette["foreground"],

                "opacityManaged":
                    True,

                "strongColors":
                    palette[
                        "strong_colors"
                    ],

                "autoThemes":
                    auto_themes,

                "autoThemeBackups":
                    auto_theme_backups,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    return palette


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Sync Kitty colors with "
            "the live Velora bar surface."
        )
    )

    parser.add_argument(
        "--quiet",
        action="store_true",
    )

    args = parser.parse_args()

    try:
        palette = (
            sync_terminal_theme()
        )

    except Exception as exc:
        print(
            f"velora-terminal-theme: {exc}",
            file=sys.stderr,
        )

        return 1

    if not args.quiet:
        print(
            "terminal-theme=kitty "
            f"background={palette['background']} "
            f"opacity={palette['background_opacity']:.3f} "
            f"foreground={palette['foreground']} "
            f"strong_colors="
            f"{'on' if palette['strong_colors'] else 'off'}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
